### ISSUE TITLE
Where did this version of check variable go?  

### ISSUE THREAD

**Issue by EdenTheBoa** [Lucasamiel0406/DBM_check_variable#1]
Even the one from DBM mods doesn't have check full regex and other options. Of course the options I need are removed or something like that. please correct me if i am wrong.

**Comment by Lucasamiel0406** [comment]
DBM Mods removed the `Check Variable` action since it was revamped on the new version.

This documentation is mostly to make people learn the usage of **Strings**, **Numbers** and similar on Check Variable, which causes a lot of issues (stated on the docs), your issue with the action shouldn't be brought here, but on both DBM servers.
You also didn't provided enough information for me when I asked what was happening on your issue, helpers can't do much with no information, but anyways.

I'll contact you soon on the main server to deal with that Check Variable issue.
